// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJYBt35PVHE_DDN-CNkWC8vJzhdp9-tM',
    appId: '1:528244949384:web:0bcc66dd750bbddec7fa3d',
    messagingSenderId: '528244949384',
    projectId: 'myproject-391913',
    authDomain: 'myproject-391913.firebaseapp.com',
    databaseURL: 'https://myproject-391913-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-391913.appspot.com',
    measurementId: 'G-1V96XKL34V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl40zFcOkrHHqa3RyvJo_GMLN8TeDjWv8',
    appId: '1:528244949384:android:673bdb4e3c81d780c7fa3d',
    messagingSenderId: '528244949384',
    projectId: 'myproject-391913',
    storageBucket: 'myproject-391913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGLrBESR6cRH4mEgoOQSiHjRpYVv2xCk',
    appId: '1:528244949384:ios:b45a5c2e53b5591fc7fa3d',
    messagingSenderId: '528244949384',
    projectId: 'myproject-391913',
    databaseURL: 'https://myproject-391913-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-391913.appspot.com',
    androidClientId: '528244949384-im2f1juqgr52ni0sh2aib9d0tv9v096e.apps.googleusercontent.com',
    iosBundleId: 'com.example.marioGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGLrBESR6cRH4mEgoOQSiHjRpYVv2xCk',
    appId: '1:528244949384:ios:e6dbadbd99b7f178c7fa3d',
    messagingSenderId: '528244949384',
    projectId: 'myproject-391913',
    databaseURL: 'https://myproject-391913-default-rtdb.firebaseio.com',
    storageBucket: 'myproject-391913.appspot.com',
    androidClientId: '528244949384-im2f1juqgr52ni0sh2aib9d0tv9v096e.apps.googleusercontent.com',
    iosBundleId: 'com.example.marioGame.RunnerTests',
  );
}
